[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.flake8]
doctests = true

[tool.isort]
force_single_line = true
combine_as_imports = true
sections = ["FUTURE","STDLIB","THIRDPARTY","FIRSTPARTY","LOCALFOLDER"]
known_third_party = ["six","docutils","pkg_resources","pytz"]
line_length = 80
lines_after_imports = 2
